In [1]:
from torch.nn import Softmax
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')
compute_softmax = Softmax(dim=1)

model_output <br>
{'class_description_1': score_1, 'class_description_2': score_2} <br>
It is important to keep the raw score, such as cosine sim, without softmax all the scores, so that we know the extent of distance between vectors, thereby the degree of "clear cut" prediction or "borderline" prediction can be analyzed. <br>

In [2]:
# Two lists of sentences
events = ['A train accident occured yesterday',
             'Many people like to travel by train',
             'Minister John Doe is facing legal proceedings']

topics = ['traffic accident or disruption',
              'lawsuits or insurance news',
              'leisure news or other news']

# for event in events:
#     event_emb = model.encode(event, convert_to_tensor=True)
#     for topic in topics:
#         topic_emb = model.encode(topic, convert_to_tensor=True)
#         cosine_score = util.cos_sim(event_emb, topic_emb)
#         print(event)
#         print(topic)
#         print(cosine_score)
#         print()

def compute_similar_topics(input_text:str, topics:list):
    topic_embs = model.encode(topics)
    text_emb = model.encode([input_text])
    cosine_scores = util.cos_sim(text_emb, topic_embs)
    cosine_scores_softmax = compute_softmax(cosine_scores)
    most_similar_topic = topics[cosine_scores.argmax()]
    return most_similar_topic, cosine_scores, cosine_scores_softmax

compute_similar_topics(events[-1], topics)


('lawsuits or insurance news',
 tensor([[0.1381, 0.2609, 0.0382]]),
 tensor([[0.3294, 0.3725, 0.2981]]))

In [20]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Assuming you have the embeddings and sentences as provided in your question
# embeddings1 and embeddings2

# Initialize an empty matrix to store cosine similarity scores
cosine_matrix = np.zeros((len(sentences1), len(sentences2)))

# Calculate cosine similarities and fill the matrix
for i in range(len(sentences1)):
    for j in range(len(sentences2)):
        # Calculate cosine similarity between sentence i from list 1 and sentence j from list 2
        cosine_score = util.cos_sim(embeddings1[i], embeddings2[j])
        cosine_matrix[i, j] = cosine_score

# Extract the lower triangular part of the matrix (including the diagonal)
lower_triangular = np.tril(cosine_matrix)

# Find the indices of non-zero elements in the lower triangular part
row_indices, col_indices = np.where(lower_triangular > 0)

# Extract the respective elements in the two text lists
similar_sentences1 = [sentences1[i] for i in row_indices]
similar_sentences2 = [sentences2[j] for j in col_indices]

# Print the similar sentences and their cosine similarity values
for i, j in zip(row_indices, col_indices):
    print("Sentence 1:", sentences1[i])
    print("Sentence 2:", sentences2[j])
    print("Cosine Similarity:", cosine_matrix[i, j])
    print()



Sentence 1: A train accident occured yesterday
Sentence 2: road traffic accident or disruption
Cosine Similarity: 0.5312840342521667

Sentence 1: Many people like to travel by train
Sentence 2: road traffic accident or disruption
Cosine Similarity: 0.18593277037143707

Sentence 1: Many people like to travel by train
Sentence 2: maritime traffic accident or disruption
Cosine Similarity: 0.24450285732746124

Sentence 1: dozens got hurt but noone is killed in a road accident
Sentence 2: road traffic accident or disruption
Cosine Similarity: 0.5538912415504456

Sentence 1: dozens got hurt but noone is killed in a road accident
Sentence 2: maritime traffic accident or disruption
Cosine Similarity: 0.389691025018692

Sentence 1: dozens got hurt but noone is killed in a road accident
Sentence 2: air traffic accident or disruption
Cosine Similarity: 0.437001496553421



In [13]:
cosine_matrix

array([[0.55056399, 0.55056399, 0.55056405],
       [0.19907561, 0.19907561, 0.19907562],
       [0.5540725 , 0.5540725 , 0.5540725 ]])